import type { ConnectorDefinition } from "../types";

const honestHeaders = {
  "User-Agent": "OPWatch/1.0 (+personal read-only stock monitor)",
  "Accept": "text/html,application/xhtml+xml;q=0.9,*/*;q=0.5",
  "Accept-Language": "fr-FR,fr;q=0.9,en;q=0.6"
};

export const ludisphere: ConnectorDefinition = { key: "ludisphere", name: "Ludisphere", sources: ["https://ludisphere.fr/collections/one-piece-card-game-precommande"], productUrlPatterns: [/\/products\/[^?#]+/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Catalogue One Piece public avec VF/EN explicites."] };
export const parkage: ConnectorDefinition = { key: "parkage", name: "Parkage", sources: ["https://www.parkage.com/fr/one-piece-card-game?language%5B%5D=fr", "https://www.parkage.com/fr/pack-spciaux-one-piece-card-game", "https://www.parkage.com/fr/deck-one-piece-card-game"], productUrlPatterns: [/\/fr\/\d{6,}-[^?#]+/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["403/429 = source dégradée, jamais rupture."] };
export const ultrajeux: ConnectorDefinition = { key: "ultrajeux", name: "UltraJeux", sources: ["https://www.ultrajeux.com/cat.php?jeu=1031", "https://www.ultrajeux.com/cat.php?cat=1&jeu=1031"], productUrlPatterns: [/\/produit-\d+-[^?#]+\.html/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Catalogue public avec catégories FR/EN."] };
export const playin: ConnectorDefinition = { key: "playin", name: "Playin", sources: ["https://www.play-in.com/fr/gamme/24/one-piece/catalogue", "https://www.play-in.com/fr/categorie/335/booster-et-boite-one-piece"], productUrlPatterns: [/\/fr\/produit\/\d+\/[^?#]+/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Fiches produit séparées des événements."] };
export const philibert: ConnectorDefinition = { key: "philibert", name: "Philibert", sources: ["https://www.philibertnet.com/fr/17214-one-piece-le-jeu-de-cartes"], productUrlPatterns: [/\/fr\/[^/]+\/\d+-[^?#]+\.html/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Catégorie française dédiée."] };
export const cultura: ConnectorDefinition = { key: "cultura", name: "Cultura", sources: ["https://www.cultura.com/cartes-a-jouer/cartes-one-piece.html"], productUrlPatterns: [/\/p-[^?#]+-\d+\.html/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Catalogue FR/JP et marketplace : langue stricte."] };
export const micromania: ConnectorDefinition = { key: "micromania", name: "Micromania", sources: ["https://www.micromania.fr/search?q=one%20piece%20booster"], productUrlPatterns: [/https?:\/\/(?:www\.)?micromania\.fr\/[^?#]+\.html/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 16, notes: ["Recherche publique à valider par runtime."] };
export const fnac: ConnectorDefinition = { key: "fnac", name: "Fnac", sources: ["https://www.fnac.com/One-Piece/m285486/w-4"], productUrlPatterns: [/\/[^?#/]+\/a\d+\/w-4/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, requiredSellerPatterns: [/\bvendu(?:e)?\s+(?:et\s+expédié(?:e)?\s+)?par\s+(?:la\s+)?fnac\b/i], requiredSellerLabel: "Fnac", notes: ["Marketplace : vendeur Fnac requis pour alerte commerciale."] };
export const leclerc: ConnectorDefinition = { key: "leclerc", name: "E.Leclerc", sources: ["https://www.e.leclerc/recherche?q=one%20piece%20booster"], productUrlPatterns: [/\/fp\/[^?#]+/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, requiredSellerPatterns: [/\bvendu\s+par\s+e\.?leclerc\b/i, /\bsnc\s+lcommerce\b/i], requiredSellerLabel: "E.Leclerc", notes: ["Marketplace : vendeur E.Leclerc requis."] };
export const carrefour: ConnectorDefinition = { key: "carrefour", name: "Carrefour", sources: ["https://www.carrefour.fr/s?q=one%20piece%20booster"], productUrlPatterns: [/\/p\/[^?#]+/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, requiredSellerPatterns: [/\bvendu(?:e)?\s+(?:et\s+expédié(?:e)?\s+)?par\s+carrefour\b/i], requiredSellerLabel: "Carrefour", notes: ["Marketplace : vendeur Carrefour requis."] };
export const kingJouet: ConnectorDefinition = { key: "king-jouet", name: "King Jouet", sources: ["https://www.king-jouet.com/jeux-jouets/one-piece/asmodee-cartes-a-collectionner/page1.htm"], productUrlPatterns: [/\/jeu-jouet\/[^?#]+\/ref-\d+-[^?#]+\.htm/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Catégorie One Piece cartes à collectionner."] };
export const joueclub: ConnectorDefinition = { key: "joueclub", name: "JouéClub", sources: ["https://www.joueclub.fr/one-piece/liste-des-produits.html"], productUrlPatterns: [/\/one-piece\/[^?#]+-\d+\.html/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Stock catalogue Web/Magasin ; fiches parfois Angular."] };
export const amazonFr: ConnectorDefinition = { key: "amazon-fr", name: "Amazon FR", sources: ["https://www.amazon.fr/s?k=one+piece+card+game+francais"], productUrlPatterns: [/\/dp\/[A-Z0-9]{8,12}/i, /\/gp\/product\/[A-Z0-9]{8,12}/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 12, requiresDirectProductPageForAlerts: true, requiredSellerPatterns: [/\bvendu\s+par\s+amazon\b/i, /\bexpédié(?:e)?\s+par\s+amazon\b/i], requiredSellerLabel: "Amazon", notes: ["Anti-bot/marketplace à haut risque."] };
export const mysticAmbre: ConnectorDefinition = { key: "mystic-ambre", name: "Mystic-Ambre", sources: ["https://www.mystic-ambre.fr/boutique/pre-commande/one-piece-pre-co/", "https://www.mystic-ambre.fr/boutique/pre-commande/one-piece-pre-co/display-one-piece-fr/"], productUrlPatterns: [/\/boutique\/[^?#]+\.html/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Précommandes FR/EN explicites."] };
export const ludiworld: ConnectorDefinition = { key: "ludiworld", name: "Ludiworld", sources: ["https://www.ludiworld.com/", "https://www.ludiworld.com/search?q=one%20piece"], productUrlPatterns: [/\/products\/[^?#]+/i, /\/product\/[^?#]+/i, /\/produit\/[^?#]+/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 16, notes: ["Robots crawler externe != blocage Worker ; runtime seul fait foi."] };
export const vegastore: ConnectorDefinition = { key: "vegastore", name: "VegaStore", sources: ["https://www.vegastore.fr/collections/one-piece", "https://www.vegastore.fr/products/display-one-piece-op-17-boite-de-24-boosters-francais"], productUrlPatterns: [/\/products\/[^?#]+/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, notes: ["Shopify public et fiche OP17 FR témoin."] };
export const otakuland: ConnectorDefinition = { key: "otakuland", name: "Otakuland", sources: ["https://otakuland.fr/", "https://otakuland.fr/?s=one+piece&post_type=product"], productUrlPatterns: [/https?:\/\/(?:www\.)?otakuland\.fr\/(?!cart|checkout|my-account)[^?#]+\/?$/i], requestHeaders: honestHeaders, followDiscoveredProductPages: true, maxDiscoveredProductPages: 12, notes: ["Catalogue observé actuellement merchandising ; 0 TCG est un résultat valide."] };

export const ROLLOUT_CONNECTORS: ConnectorDefinition[] = [ludisphere, parkage, ultrajeux, playin, philibert, cultura, micromania, fnac, leclerc, carrefour, kingJouet, joueclub, amazonFr, mysticAmbre, ludiworld, vegastore, otakuland];
