import type { ConnectorDefinition } from "../types";

const honestHeaders = {
  "User-Agent": "OPWatch/1.0 (+personal read-only stock monitor)",
  "Accept": "text/html,application/xhtml+xml;q=0.9,*/*;q=0.5",
  "Accept-Language": "fr-FR,fr;q=0.9,en;q=0.6"
};
const onePieceMarker = [/one[\s-]*piece/i];

function canonicalAmazonProductUrl(value: string): string {
  const url = new URL(value);
  if (!/(?:^|\.)amazon\.fr$/i.test(url.hostname)) return value;
  const asin = url.pathname.match(/\/(?:dp|gp\/product)\/([A-Z0-9]{8,12})(?:\/|$)/i)?.[1];
  return asin ? `https://www.amazon.fr/dp/${asin.toUpperCase()}` : value;
}

export const ludisphere: ConnectorDefinition = { key: "ludisphere", name: "Ludisphere", sources: ["https://020d06-2.myshopify.com/collections/one-piece-card-game-precommande/products.json?limit=250"], productUrlPatterns: [/\/products\/[^?#]+/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, authoritativeStructuredFeed: true, notes: ["Flux Shopify JSON public : variantes, prix, stock et images structurés."] };
export const parkage: ConnectorDefinition = { key: "parkage", name: "Parkage", sources: ["https://www.parkage.com/fr/one-piece-card-game?language%5B%5D=fr", "https://www.parkage.com/fr/pack-spciaux-one-piece-card-game", "https://www.parkage.com/fr/decks-one-piece-card-game", "https://www.parkage.com/fr/1116903-one-piece-card-game-starter-deck-st-31", "https://www.parkage.com/fr/1116904-one-piece-card-game-starter-deck-st-32", "https://www.parkage.com/fr/1116905-one-piece-card-game-starter-deck-st-33", "https://www.parkage.com/fr/1116906-one-piece-card-game-starter-deck-st-34", "https://www.parkage.com/fr/1116907-one-piece-card-game-starter-deck-st-35", "https://www.parkage.com/fr/1116908-one-piece-card-game-starter-deck-st-36"], productUrlPatterns: [/\/fr\/\d{6,}-[^?#]+/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, notes: ["La catégorie actuelle hydrate ses cartes en JavaScript : les fiches ST31-ST36 servent aussi de seeds directes pour éviter un faux catalogue vide.", "403/429 = source dégradée, jamais rupture."] };
export const ultrajeux: ConnectorDefinition = { key: "ultrajeux", name: "UltraJeux", sources: ["https://www.ultrajeux.com/cat.php?jeu=1031", "https://www.ultrajeux.com/cat.php?cat=1&jeu=1031"], productUrlPatterns: [/\/produit-\d+-[^?#]+\.html/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, notes: ["Catalogue public avec catégories FR/EN."] };
export const playin: ConnectorDefinition = { key: "playin", name: "Playin", sources: ["https://www.play-in.com/fr/produit/646300/display-de-24-boosters-op-16-l-heure-de-la-bataille-decisive-one-piece-fr", "https://www.play-in.com/fr/produit/646299/booster-op-16-l-heure-de-la-bataille-decisive-one-piece-fr", "https://www.play-in.com/fr/produit/650306/double-pack-set-11-l-heure-de-la-bataille-decisive-op-16-one-piece-fr", "https://www.play-in.com/fr/produit/646315/display-de-24-boosters-op-16-l-heure-de-la-bataille-decisive-one-piece-en"], productUrlPatterns: [/\/fr\/produit\/\d+\/[^?#]+/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, authorizedFeedEnv: "AUTHORIZED_FEED_PLAYIN_URL", directPollingDisabledWithoutFeed: true, notes: ["Origine protégée par Cloudflare : Fast Watch doit utiliser le flux produit partenaire autorisé dès qu'il est configuré.", "La découverte de nouvelles URLs reste séparée du Fast Watch."] };
export const philibert: ConnectorDefinition = { key: "philibert", name: "Philibert", sources: ["https://www.philibertnet.com/fr/17214-one-piece-le-jeu-de-cartes"], productUrlPatterns: [/\/fr\/[^/]+\/\d+-[^?#]+\.html/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, notes: ["Catégorie française dédiée."] };
export const cultura: ConnectorDefinition = { key: "cultura", name: "Cultura", sources: ["https://www.cultura.com/p-booster-one-piece-op16-l-heure-de-la-bataille-decisive-13080126.html", "https://www.cultura.com/p-booster-one-piece-les-sept-de-la-mer-d-azur-bandai-12777658.html"], productUrlPatterns: [/\/p-[^?#]+-\d+\.html/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiredSellerPatterns: [/\bvendu(?:e)?(?:\s+et\s+expédié(?:e)?)?\s+par\s*:?\s*cultura\b/i, /^cultura$/i], requiredSellerLabel: "Cultura", authorizedFeedEnv: "AUTHORIZED_FEED_CULTURA_URL", directPollingDisabledWithoutFeed: true, notes: ["Origine protégée : Fast Watch doit utiliser le flux produit partenaire autorisé dès qu'il est configuré.", "Marketplace : vendeur Cultura obligatoire ; FR/JP restent filtrés strictement."] };
export const micromania: ConnectorDefinition = { key: "micromania", name: "Micromania", sources: ["https://www.micromania.fr/search?q=one%20piece%20booster"], productUrlPatterns: [/https?:\/\/(?:www\.)?micromania\.fr\/[^?#]+\.html/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 16, authorizedFeedEnv: "AUTHORIZED_FEED_MICROMANIA_URL", directPollingDisabledWithoutFeed: true, notes: ["L'origine renvoie un shell anti-bot trompeur : Fast Watch doit utiliser un flux produit partenaire autorisé."] };
export const fnac: ConnectorDefinition = { key: "fnac", name: "Fnac", sources: ["https://www.fnac.com/Cartes-a-collectionner-One-Piece-OP16-Booster-Double-Pack/a23123806/w-4", "https://www.fnac.com/Cartes-a-collectionner-One-Piece-OP16-Booster-Blister/a23123796/w-4"], productUrlPatterns: [/\/[^?#/]+\/a\d+\/w-4/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, requiredSellerPatterns: [/\bvendu(?:e)?\s+(?:et\s+expédié(?:e)?\s+)?par\s+(?:la\s+)?fnac(?:\.com)?\b/i, /^(?:la\s+)?fnac(?:\.com)?$/i], requiredSellerLabel: "Fnac", authorizedFeedEnv: "AUTHORIZED_FEED_FNAC_URL", directPollingDisabledWithoutFeed: true, notes: ["DataDome protège les fiches directes : Fast Watch doit utiliser le flux produit partenaire autorisé.", "Marketplace : le vendeur Fnac doit rester explicitement confirmé dans le flux avant alerte."] };
export const leclerc: ConnectorDefinition = { key: "leclerc", name: "E.Leclerc", sources: ["https://www.e.leclerc/recherche?q=one%20piece%20booster"], productUrlPatterns: [/\/fp\/[^?#]+/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, notes: ["Marketplace E.Leclerc autorisée : le vendeur est informatif mais n'est plus un motif de rejet. OP Watch ne prétend jamais qu'une offre est vendue par E.Leclerc sans preuve."] };
export const carrefour: ConnectorDefinition = { key: "carrefour", name: "Carrefour", sources: ["https://www.carrefour.fr/p/cartes-booster-one-piece-op14-les-sept-de-la-mer-d-azur-bandai-4582769923166", "https://www.carrefour.fr/p/carte-a-collectionner-one-piece-coffret-decouverte-apprenez-ensemble-4582769913051"], productUrlPatterns: [/\/p\/[^?#]+/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, requiredSellerPatterns: [/\bvendu(?:e)?\s+(?:et\s+livré(?:e)?\s+)?par\s+carrefour\b/i, /\bvendu\s+par\s+carrefour\b/i, /^carrefour$/i], requiredSellerLabel: "Carrefour", authorizedFeedEnv: "AUTHORIZED_FEED_CARREFOUR_URL", directPollingDisabledWithoutFeed: true, notes: ["Origine protégée : Fast Watch doit utiliser le flux produit partenaire autorisé.", "Marketplace : vendeur Carrefour obligatoire avant alerte."] };
export const kingJouet: ConnectorDefinition = { key: "king-jouet", name: "King Jouet", sources: ["https://www.king-jouet.com/jeux-jouets/tous-les-jouets-one-piece/jeux-societes/page1.htm", "https://www.king-jouet.com/jeu-jouet/jeux-societes/cartes-a-collectionner/ref-1034198-cartes-one-piece-booster-op16-heure-de-la-bataille-decisive.htm", "https://www.king-jouet.com/jeu-jouet/jeux-societes/cartes-a-collectionner/ref-1034904-cartes-one-piece-double-booster-op16-heure-de-la-bataille-decisive.htm"], productUrlPatterns: [/\/jeu-jouet\/[^?#]+\/ref-\d+-[^?#]+\.htm/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, authorizedFeedEnv: "AUTHORIZED_FEED_KING_JOUET_URL", directPollingDisabledWithoutFeed: true, notes: ["DataDome protège les fiches directes et l'API Cataleeze documentée exige une autorisation : Fast Watch doit utiliser un flux produit partenaire autorisé."] };
export const joueclub: ConnectorDefinition = { key: "joueclub", name: "JouéClub", sources: ["https://www.joueclub.fr/one-piece/liste-des-produits.html"], productUrlPatterns: [/\/one-piece\/[^?#]+-\d+\.html/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, notes: ["Stock catalogue Web/Magasin ; fiches parfois Angular."] };
export const amazonFr: ConnectorDefinition = { key: "amazon-fr", name: "Amazon FR", sources: ["https://www.amazon.fr/s?k=one+piece+card+game+francais"], productUrlPatterns: [/\/dp\/[A-Z0-9]{8,12}/i, /\/gp\/product\/[A-Z0-9]{8,12}/i], canonicalizeProductUrl: canonicalAmazonProductUrl, requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 12, requiresDirectProductPageForAlerts: true, requiredSellerPatterns: [/\bvendu\s+par\s+amazon(?:\.fr)?\b/i, /^amazon(?:\.fr)?$/i], requiredSellerLabel: "Amazon", notes: ["Les variantes de tracking d'un même ASIN sont ramenées à une fiche canonique unique.", "Anti-bot/marketplace à haut risque ; Robot Check/CAPTCHA est explicitement rejeté.", "Expédié par Amazon seul ne suffit pas : le vendeur doit être Amazon."] };
export const mysticAmbre: ConnectorDefinition = { key: "mystic-ambre", name: "Mystic-Ambre", sources: ["https://www.mystic-ambre.fr/boutique/pre-commande/one-piece-pre-co/", "https://www.mystic-ambre.fr/boutique/pre-commande/one-piece-pre-co/display-one-piece-fr/"], productUrlPatterns: [/\/boutique\/[^?#]+\.html/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, notes: ["Précommandes FR/EN explicites."] };
export const ludiworld: ConnectorDefinition = { key: "ludiworld", name: "Ludiworld", sources: ["https://www.ludiworld.com/"], productUrlPatterns: [/\/products\/[^?#]+/i, /\/product\/[^?#]+/i, /\/produit\/[^?#]+/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 16, commercialAlertsEnabled: false, notes: ["La fausse route /search a été supprimée.", "La racine seule ne sera considérée valide que si elle expose effectivement One Piece ; alertes commerciales désactivées tant qu'une route TCG fiable n'est pas validée."] };
export const vegastore: ConnectorDefinition = { key: "vegastore", name: "VegaStore", sources: ["https://www.vegastore.fr/collections/one-piece", "https://www.vegastore.fr/products/display-one-piece-op-17-boite-de-24-boosters-francais"], productUrlPatterns: [/\/products\/[^?#]+/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 20, requiresDirectProductPageForAlerts: true, notes: ["Shopify public et fiche OP17 FR témoin."] };
export const otakuland: ConnectorDefinition = { key: "otakuland", name: "Otakuland", sources: ["https://otakuland.fr/shop/", "https://otakuland.fr/otakuland/"], productUrlPatterns: [/https?:\/\/(?:www\.)?otakuland\.fr\/(?!cart|checkout|my-account)[^?#]+\/?$/i], requestHeaders: honestHeaders, responseMustContainAny: onePieceMarker, followDiscoveredProductPages: true, maxDiscoveredProductPages: 12, commercialAlertsEnabled: false, notes: ["Catalogue public observé : merchandising/figurines, aucun TCG One Piece identifié actuellement.", "Discovery-only : aucune alerte commerciale tant qu'une offre TCG n'est pas réellement observée et validée."] };

export const ROLLOUT_CONNECTORS: ConnectorDefinition[] = [ludisphere, parkage, ultrajeux, playin, philibert, cultura, micromania, fnac, leclerc, carrefour, kingJouet, joueclub, amazonFr, mysticAmbre, ludiworld, vegastore, otakuland];
